### ISSUE TITLE
Format on file change

### ISSUE THREAD

**Issue by LandonSchropp** [alexgavrusev/obsidian-format-with-prettier#23]
Thank you for creating this plugin!

The Linter plugin features an option, "Lint on File change," which lists the file every time it's closed or switched away from.

![Screenshot 2024-09-15 at 9 58 21 AM](https://github.com/user-attachments/assets/8582bcab-1c6a-4f26-b9a9-0d42ade7adbf)

Since Obsidian has autosave functionality, this allows files to be linted in the background, without any explicit saves required.

It'd be cool if this plugin could support the same feature. 🙂

**Comment by alexgavrusev** [comment]
@LandonSchropp Hey, sorry for the late reply, finally got the time to take a look at what it would take to implement this.

Looks like this will require some extensive work, so I can't promise any concrete timeline for now

**Comment by alexgavrusev** [comment]
In the end, I've decided against implementing this feature, as it'd increase the maintenance burden by too much, given the amount of edgecases of `active-leaf-change`
